# PyTorch fundamentals

---

## Part 1: Tensor Basics

In [1]:
import torch

# Creating a scalar
tensor_scalar = torch.tensor(7)
tensor_scalar

tensor(7)

In [2]:
# Creating a vector
tensor_vector = torch.tensor([7, 8])
tensor_vector

tensor([7, 8])

In [3]:
# Creating a matrix
tensor_matrix = torch.tensor([[7, 8], [9, 10]])
tensor_matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [4]:
# Creating a tensor with more dimensions
tensor_multi = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor_multi

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [5]:
# Shape of a tensor
tensor_multi.shape

torch.Size([1, 3, 3])

In [6]:
# Indexing in tensor
x = torch.tensor([[[1, 9, 17], [25, 33, 41], [49, 57, 65]]])
x[0, 0, :]

tensor([ 1,  9, 17])

In [7]:
# Accessing specific value from tensor
x[0, 2, 1]

tensor(57)

## Part 2: Tensor Operations

In [8]:
import torch

# Element-wise multiplication
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])
tensor_1 * tensor_2

tensor([ 4, 10, 18])

In [9]:
# Matrix multiplication using matmul
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
torch.matmul(a, b)

tensor([[19, 22],
        [43, 50]])

In [10]:
# Matrix multiplication using @
a @ b

tensor([[19, 22],
        [43, 50]])

In [11]:
# Aggregation
x = torch.tensor([1.0, 2.0, 3.0])
x.mean(), x.sum(), x.max(), x.min()

(tensor(2.), tensor(6.), tensor(3.), tensor(1.))

## Part 3: NumPy and PyTorch

In [12]:
import numpy as np
import torch

# NumPy to tensor
arr = np.arange(1., 10.)
tensor_from_np = torch.from_numpy(arr)
arr, tensor_from_np

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [13]:
# Changing numpy array doesn't change tensor
arr = arr + 1
arr, tensor_from_np

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [14]:
# Tensor to NumPy
Ten1 = torch.arange(1.0, 18, 2)
array1 = Ten1.numpy()
array1, Ten1

(array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.], dtype=float32),
 tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.]))

In [15]:
# Changing tensor doesn't affect numpy array
Ten1 = Ten1 + 1
Ten1, array1

(tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]),
 array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.], dtype=float32))

## Part 4: Random Seed

In [16]:
import torch

# Without seed
tensor_a = torch.rand(2, 4)
tensor_b = torch.rand(2, 4)
tensor_a, tensor_b, tensor_a == tensor_b

(tensor([[0.4177, 0.8306, 0.7310, 0.0244],
         [0.5350, 0.5360, 0.1067, 0.5349]]),
 tensor([[0.8249, 0.5309, 0.1445, 0.3690],
         [0.5079, 0.0775, 0.0374, 0.0921]]),
 tensor([[False, False, False, False],
         [False, False, False, False]]))

In [17]:
# With manual seed
random_seed = 42
torch.manual_seed(random_seed)
tensor_a = torch.rand(2, 4)
torch.manual_seed(random_seed)
tensor_b = torch.rand(2, 4)
tensor_a, tensor_b, tensor_a == tensor_b

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936]]),
 tensor([[True, True, True, True],
         [True, True, True, True]]))

## Part 5: GPU Support in PyTorch

In [18]:
import torch

# Check if GPU is available
torch.cuda.is_available()

False

In [19]:
# Create tensor on CPU
Tensor_on_cpu = torch.tensor([1, 9, 20])
Tensor_on_cpu.device

device(type='cpu')

In [20]:
# Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [21]:
# Move tensor to GPU
Tensor_on_gpu = Tensor_on_cpu.to(device)
Tensor_on_gpu.device

device(type='cpu')

In [22]:
# Convert back to CPU before converting to numpy
tensor_back_on_cpu = Tensor_on_gpu.cpu()
array_from_tensor = tensor_back_on_cpu.numpy()
array_from_tensor

array([ 1,  9, 20])

## Part 6: Tensor Reshaping and Stacking

In [23]:
import torch

# Reshape tensor
a = torch.arange(1, 10)
a_reshaped = a.reshape(3, 3)
a_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
# View tensor with same shape
b = a.view(3, 3)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
# Squeeze and Unsqueeze
c = torch.tensor([[[1], [2], [3]]])
c_squeezed = c.squeeze()
c_unsqueezed = c_squeezed.unsqueeze(1)
c_squeezed, c_unsqueezed

(tensor([1, 2, 3]),
 tensor([[1],
         [2],
         [3]]))

In [26]:
# Stacking tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
stacked = torch.stack((x, y))
stacked

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
# Concatenating tensors
cat_axis0 = torch.cat((x.unsqueeze(0), y.unsqueeze(0)), dim=0)
cat_axis1 = torch.cat((x.unsqueeze(1), y.unsqueeze(1)), dim=1)
cat_axis0, cat_axis1

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))