In [1]:
import torch


scalar, vector, matrix , tensor

In [2]:
# Scalar (0D Tensor)
scalar = torch.tensor(5)
print("Scalar:", scalar)
print("Dimensions:", scalar.ndim)
print("Item:", scalar.item())  # Gets the value inside


Scalar: tensor(5)
Dimensions: 0
Item: 5


In [3]:
# Vector (1D Tensor)
vector = torch.tensor([1, 2, 3])
print("Vector:", vector)
print("Dimensions:", vector.ndim)


Vector: tensor([1, 2, 3])
Dimensions: 1


In [4]:
# Matrix (2D Tensor)
matrix = torch.tensor([[1, 2], [3, 4]])
print("Matrix:\n", matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)


Matrix:
 tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])
Dimensions: 2


In [5]:
# 3D Tensor
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Tensor:\n", tensor_3d)
print("Shape:", tensor_3d.shape)
print("Dimensions:", tensor_3d.ndim)


3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Dimensions: 3


Tensors with zeroes, ones and Random

In [6]:
zeros = torch.zeros(2, 3)
print("Zeros:\n", zeros)

ones = torch.ones(2, 3)
print("Ones:\n", ones)

random = torch.rand(2, 3)
print("Random:\n", random)


Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random:
 tensor([[0.2636, 0.6562, 0.9780],
        [0.9198, 0.2930, 0.8746]])


Tensors from a range

In [7]:
range_tensor = torch.arange(0, 18, 2)
print("Range Tensor:", range_tensor)


Range Tensor: tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])


Tensor Math

In [8]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print("Addition:", x + y)
print("Multiplication:", x * y)
print("Power:", x ** 2)
print("Matrix dot product:", torch.dot(x.float(), y.float()))


Addition: tensor([5, 7, 9])
Multiplication: tensor([ 4, 10, 18])
Power: tensor([1, 4, 9])
Matrix dot product: tensor(32.)
